version: '3'

services:
  streamlit:
    image: qrcode_gen_webapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10201:8080"
    environment:
      API_KEY: "atolovekey" # 여기에 API 키를 채워넣으세요.
    volumes:
      - ./app:/app # 현재 디렉토리를 컨테이너의 /app 디렉토리에 바인드
    restart: always
